name: nail_connect_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  device_info_plus: ^12.2.0
  dropdown_button2: ^2.3.9
  firebase_storage: ^13.0.3
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  pinput: ^5.0.2
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
